services:
  homeassistant:
    image: ghcr.io/home-assistant/home-assistant:stable
    container_name: homeassistant
    network_mode: host
    restart: unless-stopped
    environment:
      - TZ=${TZ:-America/New_York}
    volumes:
      - ${HA_DATA:-/opt/homeassistant}:/config
